# # Getting Started

# This guide walks through a complete first workflow with `XAIMetrics.jl`:
#
# 1. define a model and explanation method,
# 2. prepare batched input,
# 3. evaluate robustness metrics,
# 4. customize perturbation and normalization behavior.
#
# !!! note
#     `XAIMetrics.jl` evaluates explanations generated by `ExplainableAI.jl` methods.

# ## Prerequisites
using XAIMetrics
using ExplainableAI
using Flux
using Random

# Create a simple classifier and an explanation method:
model = Chain(
    Flux.flatten,
    Dense(28 * 28, 64, relu),
    Dense(64, 10),
)

method = InputTimesGradient(model)

# ## Prepare input and targets
# `evaluate` expects batched input with batch dimension last.
# For image data in Flux, this is typically `WHCN`.
batch_size = 8
x = rand(Float32, 28, 28, 1, batch_size)
y = rand(1:10, batch_size)

# !!! note "Input shape"
#     The last dimension is treated as batch dimension by `XAIMetrics.jl`.

# ## First metric evaluation
# Start with `AvgSensitivity`:
metric = AvgSensitivity(
    nr_samples = 30,
    perturb_config = PerturbationConfig(
        uniform_noise!,
        (; lower = 0.05, upper = 0.1),
    ),
)

scores = evaluate(metric, method, x; y = y)

# `scores` is a vector with one score per sample in the batch.

# Then continue with `LocalLipschitzEstimate`:
lle_metric = LocalLipschitzEstimate(
    nr_samples = 50,
    perturb_config = PerturbationConfig(
        gaussian_perturbation!,
        (; std = 0.2),
    ),
    return_missing_when_prediction_changes = false,
)

lle_scores = evaluate(lle_metric, method, x; y = y)

# ## Configuring behavior
# ### Perturbations
cfg_uniform = PerturbationConfig(
    uniform_noise!,
    (; lower = 0.03, upper = 0.08))

# ### Normalization
norm_cfg = NormalizationConfig(
    normalize = true,
    normalize_func = normalize_by_max_abs,
)

metric_norm = AvgSensitivity(
    nr_samples = 30,
    perturb_config = cfg_uniform,
    normalize_config = norm_cfg,
)

# ## Inspecting perturbations
# You can also apply perturbations directly to a small input and print the result.
Random.seed!(7)

x_demo = Float32[0.2, -0.4, 0.8]
x_demo_pert = similar(x_demo)

demo_pert_cfg = PerturbationConfig(uniform_noise!, (; lower = 0.03, upper = 0.08))
perturb_input!(x_demo_pert, x_demo, demo_pert_cfg)

println("x_demo          = ", x_demo)
println("x_demo_pert     = ", x_demo_pert)
println("perturbation Δ  = ", x_demo_pert .- x_demo)

# ## Inspecting normalization
# Normalization can be inspected the same way.
a_demo = Float32[-2.0, 0.0, 1.0, 4.0]
a_norm = normalize_by_max_abs(a_demo)

println("a_demo                  = ", a_demo)
println("normalize_by_max_abs    = ", a_norm)
println("maximum(abs, a_demo)    = ", maximum(abs, a_demo))
println("maximum(abs, a_norm)    = ", maximum(abs, a_norm))

# ## Handling prediction changes
# Both robustness metrics support `return_missing_when_prediction_changes`:
#
# - `true`: return `missing` for samples where the prediction changed
# - `false`: aggregate over available finite scores
#
# This is useful when you want to separate explanation instability from class-change effects.

# ## Next steps
#
# - Robustness metric reference: [Robustness](../metrics/robustness.md)
# - Configuration overview: [Configurations](../configurations.md)
# - Function-level APIs: [Normalizations](../normalizations.md), [Perturbations](../perturbations.md), [Similarities](../similarities.md)
